spring:
  datasource:
    url: jdbc:h2:mem:benefit_db
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.domain: DEBUG
