global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'membership-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'api-gateway:8000'
          - 'member-service:8081'
          - 'payment-service:8082'
          - 'benefit-service:8083'
